### DISCUSSION TITLE
JSON Schema Linting - A call for rules

### DISCUSSION THREAD

**Discussion by gregsdennis** [json-schema-org/community#323] [General]
We're looking at putting together some official JSON Schema linting rules for Spectral!

Rules can be things like, "Your schema should have a `$schema` at the root."  (I've already included this one.)

~***To propose a rule, please create a new thread.***  We'll discuss each rule in the thread.~

**EDIT: A new repo has been created for this: https://github.com/json-schema-org/json-schema-linting**  Please create issues there for new proposals.  The proposals here will be migrated to issues there.

**Comment by gregsdennis** [comment]
We'll also need a place to store and publish the rule set.  Let's discuss that here.

**Reply by Relequestual** [reply]
I think we should create a new repo for this.

I imagine we would want the following for each rule:
- Rule name
- rule ID (string)
- description
- examples of invalid
- examples of valid
- how to fix
- default severity

I imagine we may want to provide rule groupigns, such as "essential" and "recommended".

**Reply by gregsdennis** [reply]
Looks like we have several options:  https://docs.stoplight.io/docs/spectral/7895ff1196448-sharing-and-distributing-rulesets

- local files (downloadable)
- HTTP (published on our website)
- npm

I don't think npm is going to be the best option for us since it caters to the JS crowd.  (e.g. I wouldn't be able to use that from .Net.)

**Reply by jdesrosiers** [reply]
I think ideally, we provide all of these options and people can use what's most convenient to them.

**Reply by gregsdennis** [reply]
Regarding a repo or other storage, I have quite a folder of rule files growing.  Would be great to have somewhere to put them.

**Comment by gregsdennis** [comment]
**`enum` values should validate against all adjacent keywords in a subschema.**

I see a lot of schemas where the author has specified an `enum` of values that are valid along with a `type`.

```json
{
  "type": "string",
  "enum": [
    "one",
    "two",
    3
  ]
}
```

(This example is at the root schema, but it can occur in a subschema, too.)

The problem here is that `3` doesn't meet the requirements of the rest of the keywords, which means that `3` isn't actually a valid value.

This rule would enforce that every value present in an `enum` would validate against the rest of the subschema that contains it.

**Reply by gregsdennis** [reply]
Alternatively, the rule could suggest that `type` (in this example) or other keywords are superfluous and that they should be removed.

I think this would actually be easier to configure.

**Reply by gregsdennis** [reply]
If we suggest against sibling keywords, then we can't support if they want to include `$id` or `$dynamicAnchor` or annotation-only keywords. 🤔

**Reply by jdesrosiers** [reply]
It just needs to suggest that `type` is not a sibling to `enum`/`const`. Other siblings are fine.

**Reply by gregsdennis** [reply]
What about `minLength`?  That's not really practical alongside an enum of strings.

**Reply by jdesrosiers** [reply]
Good point. We'd probably need to make a disallow list.

**Reply by gregsdennis** [reply]
This seems to work with an explicit disallow list:

```yml
enums-should-stand-alone:
  description: Enums should not have additional validation
  severity: error
  given: $..[?(@.enum)]
  then:
    - function: falsy
      field: type
    - function: falsy
      field: minimum
    - function: falsy
      field: minLength
```

Looks like this in VSCode:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/2676804/217389357-465d9794-834e-44c2-8c94-20ff3241b96b.png">

**Comment by gregsdennis** [comment]
**Validation keywords that don't operate on the specified type should be removed.**

For example:

```json
{
  "type": "object",
  "minimum": 5
}
```

`minimum` only works on numbers and will never be used.

This would be a family of rules.

**Reply by gregsdennis** [reply]
Minor hitch with this one: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/390

Can't seem to define a JSON Path that returns the root object only when a property has a certain value.

**Reply by gregsdennis** [reply]
So it started looking like I have to create a separate rule for the root object that uses a `schema` function.  That's fine, I guess.  (I solved this with a reorganization, shown later.)

The real annoyance is that `schema` functions by default only report the first error.  They can be configured to report all errors, but when you set that, the entire data instance is reported making it impossible to see where the error is actually coming from.  This means that we can't check for multiple adjacent keywords in a single rule.

For example, this doesn't work well:

```yml
keywords-with-incorrect-type-array-root:
  # This one supports the root only
  description: This keyword doesn't support arrays.
  severity: error
  given: $
  then:
    - function: schema
      functionOptions:
        schema:
          if:
            properties:
              type:
                const: array
            required:
              - type
          then:
            properties:
              minimum: false
              maximum: false
              exclusiveMinimum: false
              exclusiveMaximum: false
              multipleOf: false
              minLength: false
              maxLength: false
              pattern: false
              properties: false
              propertyName: false
              patternProperties: false
              additionalProperties: false
              unevaluatedProperties: false
              minProperties: false
              maxProperties: false
              required: false
              dependentRequired: false
              dependentSchema: false
              dependencies: false
```

If the data has `type: array` along with both a `minimum` and a `maximum`, only `minimum` is reported.  Once that's cleared, `maximum` is reported, etc.  That makes for a poor dev experience.

The solution is to break this into multiple rules.  Also, reorganizing a bit cleans things up.  This is what I came up with.  One for each keyword.

```yml
rules:
  minimum-only-applies-to-numbers-root:
    description: The minimum keyword is incompatible with the specified type.
    severity: error
    given:
      - $
      - $..[?(@.minimum!=null)]
    then:
      - function: schema
        functionOptions:
          schema:
            if:
              properties:
                type:
                  enum:
                    - object
                    - array
                    - string
                    - boolean
                    - 'null'
              required:
                - type
            then:
              properties:
                minimum: false
```

This rule checks for the `minimum` keyword and then if there's an adjacent `type` that is not either `number` or `integer`, it reports an error at the `minimum` keyword's location.  It checks for both the root and subschemas.
