### DISCUSSION TITLE
additionalProperties: false and anyOf/allOf

### DISCUSSION THREAD

**Discussion by rafalkrupinski** [json-schema-org/community#821] [Q&A] [answered]
When validating against `additionalProperties: false`, should `properties` declared under `anyOf` or `allOf` also be considered?

For example

Value:
```yaml
key: value
```

Schema:
```yaml
type: object
properties: []
additionalProperties: false
allOf:
- properties:
  - key
    type: string
```

Is the property "key" valid in this object?
